name: Lint, Build and Test

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  APP_TITLE: ${{ vars.APP_TITLE }}
  GITHUB_WORKFLOW: true

jobs:
  test:
    name: Run tests
    environment: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run test
        run: yarn test
  unimported:
    name: Find unimported files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run unimported
        run: yarn lint:unused
  lint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Lint
        run: yarn generate && yarn lint:js
  css-lint:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Css Lint
        run: yarn lint:css
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Typecheck
        run: yarn generate && yarn typecheck
  build:
    name: Build
    environment: 'Test'
    needs: [lint, css-lint, typecheck, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build
        run: yarn generate && yarn build
